display_name="DK's Barrel Blast"
description="""
DK with a recovery and a projectile?!? His new upspecial allows him to spawn barrels on the ground, or hop into a barrel cannon in the air. Spinning Kong is now down special, and his Hand Slap is now down smash!
Requires (latest) Smashline and Skyline. Will not be compatible with mods on older smashline builds.

For HDR: You might have to append the entries in hdrpatch/motion_patch.yaml to your hdr/fighter/donkey/body/motion_patch.yaml file. It's recommended you play with a custom copy of the base folder (ie hdr-custom) so that the base folder can remain 1:1 with the current HDR build
"""
version="1.0"
category="Param"
authors="C#"